# Generated by Django 2.1 on 2019-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Price'),
        ),
    ]
