# Generated by Django 2.1 on 2019-05-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0030_auto_20190515_1501'),
        ('carts', '0002_auto_20190510_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'SMALL'), ('MD', 'MEDIUM'), ('LG', 'LARGE'), ('XL', 'EXTRA LARGE'), ('XX', 'XX LARGE')], default='LG', max_length=2)),
                ('fitting', models.CharField(choices=[('SLM', 'SLIM'), ('REG', 'REGULAR'), ('RLX', 'RELAXED')], default='REG', max_length=3)),
                ('quantity', models.IntegerField(default=1, max_length=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.Shirt')),
            ],
        ),
    ]
