# Generated by Django 2.1 on 2019-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20190515_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.IntegerField(default=0, verbose_name='Shipping Charges'),
        ),
    ]
