# Generated by Django 2.1 on 2019-05-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20190515_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.IntegerField(default=0, verbose_name='No of Items'),
        ),
        migrations.AddField(
            model_name='item',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
