# Generated by Django 2.1 on 2019-03-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_shoulder', models.ImageField(upload_to='left_shoulders/', verbose_name='Left Shoulder')),
                ('r_shoulder', models.ImageField(upload_to='right_shoulders/', verbose_name='Right Shoulder')),
                ('l_front', models.ImageField(upload_to='left_fronts/', verbose_name='Left Front')),
                ('r_front', models.ImageField(upload_to='right_fronts/', verbose_name='Right Front')),
                ('l_collar_base', models.ImageField(upload_to='left_collor_bases/', verbose_name='Left Collar Base')),
                ('r_collar_base', models.ImageField(upload_to='right_color_bases/', verbose_name='Right Collar Base')),
                ('yoke_bottom', models.ImageField(upload_to='neck_bottoms/', verbose_name='Bottom Yoke')),
                ('yoke_top', models.ImageField(upload_to='neck_tops/', verbose_name='Top Yoke')),
                ('placket', models.ImageField(upload_to='plackets/', verbose_name='Placket')),
            ],
            options={
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Pattern Name')),
            ],
            options={
                'verbose_name_plural': 'Patterns',
            },
        ),
        migrations.AddField(
            model_name='base',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='shirts.Pattern'),
        ),
    ]
