# Generated by Django 2.1 on 2019-03-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0002_pattern_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularCollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner', models.ImageField(upload_to='inner_collars/')),
                ('upper', models.ImageField(upload_to='upper_collars/')),
                ('outer_r', models.ImageField(upload_to='outer_right_collars/')),
                ('outer_l', models.ImageField(upload_to='outer_left_collars/')),
                ('button', models.ImageField(upload_to='collar_buttons/')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar', to='shirts.Pattern')),
            ],
        ),
    ]
