# Generated by Django 2.1 on 2019-03-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0003_regularcollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_parts', to='shirts.Pattern'),
        ),
        migrations.AlterField(
            model_name='regularcollar',
            name='button',
            field=models.ImageField(upload_to='collar_buttons/', verbose_name='Collar Button'),
        ),
        migrations.AlterField(
            model_name='regularcollar',
            name='inner',
            field=models.ImageField(upload_to='inner_collars/', verbose_name='Inner Collar'),
        ),
        migrations.AlterField(
            model_name='regularcollar',
            name='outer_l',
            field=models.ImageField(upload_to='outer_left_collars/', verbose_name='Outer Left Collar'),
        ),
        migrations.AlterField(
            model_name='regularcollar',
            name='outer_r',
            field=models.ImageField(upload_to='outer_right_collars/', verbose_name='Outer Right Collar'),
        ),
        migrations.AlterField(
            model_name='regularcollar',
            name='upper',
            field=models.ImageField(upload_to='upper_collars/', verbose_name='Upper Collar'),
        ),
    ]
