# Generated by Django 2.1 on 2019-03-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0004_auto_20190307_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='shirts.Pattern'),
        ),
    ]
