# Generated by Django 2.1 on 2019-03-09 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0005_auto_20190308_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='pattern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shirts.Pattern'),
        ),
    ]
