# Generated by Django 2.1 on 2019-03-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0006_auto_20190309_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularcollar',
            name='pattern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shirts.Pattern'),
        ),
    ]
