# Generated by Django 2.1 on 2019-03-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0007_auto_20190309_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner', models.ImageField(upload_to='inner_collars/', verbose_name='Inner Collar')),
                ('upper', models.ImageField(upload_to='upper_collars/', verbose_name='Upper Collar')),
                ('outer_r', models.ImageField(upload_to='outer_right_collars/', verbose_name='Outer Right Collar')),
                ('outer_l', models.ImageField(upload_to='outer_left_collars/', verbose_name='Outer Left Collar')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.Pattern')),
            ],
        ),
        migrations.RemoveField(
            model_name='regularcollar',
            name='pattern',
        ),
        migrations.DeleteModel(
            name='RegularCollar',
        ),
    ]
