# Generated by Django 2.1 on 2019-03-10 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0008_auto_20190310_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='collar',
            name='catagory',
            field=models.CharField(choices=[('R', 'Regular'), ('BR', 'Big Round'), ('CA', 'Cut Away'), ('DB', 'Dual Button'), ('PH', 'Pin Hole'), ('SW', 'Semi Wide'), ('RBD', 'Round Button Down'), ('SP', 'Short Point'), ('S', 'Stand'), ('WS', 'Wide Spread')], max_length=3),
            preserve_default=False,
        ),
    ]
