# Generated by Django 2.1 on 2019-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0009_collar_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collar',
            name='catagory',
            field=models.CharField(choices=[('RR', 'Regular'), ('BR', 'Big Round'), ('CA', 'Cut Away'), ('DB', 'Dual Button'), ('PH', 'Pin Hole'), ('SW', 'Semi Wide'), ('RB', 'Round Button Down'), ('SP', 'Short Point'), ('SS', 'Stand'), ('WS', 'Wide Spread')], max_length=2),
        ),
    ]
