# Generated by Django 2.1 on 2019-03-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0010_auto_20190310_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collar',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar', to='shirts.Pattern'),
        ),
    ]
