# Generated by Django 2.1 on 2019-03-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0011_auto_20190310_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer_top', models.ImageField(upload_to='outer_top_cuffs/', verbose_name='Outer Top Cuff')),
                ('outer_bottom', models.ImageField(upload_to='outer_bottom_cuffs/', verbose_name='Outer Bottom Cuff')),
                ('inner', models.ImageField(upload_to='inner_cuffs/', verbose_name='Inner Cuff')),
                ('catagory', models.CharField(choices=[('AA', 'Angle'), ('BA', 'Big Angle'), ('BR', 'Big Round'), ('FR', 'French'), ('RR', 'Round'), ('SQ', 'Square')], max_length=2)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuff', to='shirts.Pattern')),
            ],
        ),
    ]
