# Generated by Django 2.1 on 2019-03-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0014_auto_20190317_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innercollar',
            name='upper',
        ),
    ]
