# Generated by Django 2.1 on 2019-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0015_remove_innercollar_upper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innercuff',
            name='inner_opened',
        ),
        migrations.RemoveField(
            model_name='outercuff',
            name='outer_top_opened',
        ),
        migrations.AddField(
            model_name='innercuff',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outercuff',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
