# Generated by Django 2.1 on 2019-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0016_auto_20190317_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='innercollar',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outercollar',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
