# Generated by Django 2.1 on 2019-03-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0017_auto_20190317_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innerplacket',
            old_name='inner_placket',
            new_name='inner',
        ),
        migrations.RenameField(
            model_name='outercollar',
            old_name='l_collar_base',
            new_name='l_base',
        ),
        migrations.RenameField(
            model_name='outercollar',
            old_name='r_collar_base',
            new_name='r_base',
        ),
        migrations.RenameField(
            model_name='outercuff',
            old_name='outer_bottom',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='outercuff',
            old_name='outer_top',
            new_name='top',
        ),
        migrations.RenameField(
            model_name='outerplacket',
            old_name='outer_placket',
            new_name='outer',
        ),
        migrations.RenameField(
            model_name='yoke',
            old_name='yoke_bottom',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='yoke',
            old_name='yoke_top',
            new_name='top',
        ),
        migrations.AlterField(
            model_name='innercollar',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_collar', to='shirts.Pattern'),
        ),
    ]
