# Generated by Django 2.1 on 2019-03-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0019_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name_plural': 'Background'},
        ),
    ]
