# Generated by Django 2.1 on 2019-03-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0020_auto_20190330_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_base', models.ImageField(upload_to='outer_collars/left_collor_bases/', verbose_name='Left Collar Base')),
                ('r_base', models.ImageField(upload_to='outer_collars/right_color_bases/', verbose_name='Right Collar Base')),
                ('opened', models.BooleanField(default=False)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_base', to='shirts.Pattern')),
            ],
        ),
        migrations.RemoveField(
            model_name='outercollar',
            name='l_base',
        ),
        migrations.RemoveField(
            model_name='outercollar',
            name='r_base',
        ),
    ]
