# Generated by Django 2.1 on 2019-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0021_auto_20190331_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_back', models.CharField(choices=[('SP', 'Side Pleats'), ('BP', 'Box Pleats'), ('NN', 'None')], default='NN', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('price', models.IntegerField(default=0, editable=False)),
                ('sess_id', models.IntegerField(default=None, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='shirts.Base')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button', to='shirts.Button')),
                ('collar_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_base', to='shirts.CollarBase')),
                ('inner_collar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_collar', to='shirts.InnerCollar')),
                ('inner_cuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_cuff', to='shirts.InnerCuff')),
                ('inner_placket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_placket', to='shirts.InnerPlacket')),
                ('outer_collar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer_collar', to='shirts.OuterCollar')),
                ('outer_cuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer_cuff', to='shirts.OuterCuff')),
                ('outer_placket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer_placket', to='shirts.OuterPlacket')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocket', to='shirts.Pocket')),
                ('yoke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoke', to='shirts.Yoke')),
            ],
        ),
    ]
