# Generated by Django 2.1 on 2019-04-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0022_button_pocket_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='button',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='pocket',
        ),
    ]
