# Generated by Django 2.1 on 2019-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0023_auto_20190501_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='sess_id',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
