# Generated by Django 2.1 on 2019-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0025_cart_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='sess_id',
            field=models.CharField(default='', max_length=32),
        ),
    ]
