# Generated by Django 2.1 on 2019-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0029_auto_20190510_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='shirt',
            name='price',
            field=models.IntegerField(default=12, editable=False),
        ),
    ]
