# Generated by Django 2.1 on 2019-06-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0030_auto_20190515_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32)),
                ('button', models.ImageField(upload_to='base_buttons/')),
            ],
        ),
        migrations.CreateModel(
            name='CollarButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32)),
                ('button', models.ImageField(upload_to='collar_buttons/')),
                ('catagory', models.CharField(choices=[('RR', 'Regular'), ('DB', 'Dual Button'), ('RB', 'Round Button Down')], default='RR', max_length=2)),
                ('opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Button',
            new_name='CuffButton',
        ),
    ]
