# Generated by Django 2.1 on 2019-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0031_auto_20190613_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collarbutton',
            name='catagory',
            field=models.CharField(choices=[('RR', 'Regular'), ('DB', 'Dual Button'), ('RB', 'Round Button Down'), ('PH', 'Pinhole')], default='RR', max_length=2),
        ),
    ]
