# Generated by Django 2.1 on 2019-06-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0032_auto_20190613_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuffButton',
        ),
    ]
