# Generated by Django 2.1 on 2019-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0033_delete_cuffbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuffButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32)),
                ('button', models.ImageField(upload_to='cuff_buttons/')),
                ('catagory', models.CharField(choices=[('AA', 'Angle'), ('BA', 'Big Angle'), ('BR', 'Big Round'), ('FR', 'French'), ('RR', 'Round'), ('SQ', 'Square')], default='RR', max_length=2)),
                ('opened', models.BooleanField(default=False)),
            ],
        ),
    ]
