# Generated by Django 2.1 on 2019-06-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0034_cuffbutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pocket',
        ),
    ]
