# Generated by Django 2.1 on 2019-06-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0035_delete_pocket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket', models.ImageField(upload_to='pockets/')),
                ('visible', models.BooleanField(default=False)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.Pattern')),
            ],
        ),
    ]
