# Generated by Django 2.1 on 2019-06-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0038_auto_20190622_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='base_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_button', to='shirts.BaseButton'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='collar_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_button', to='shirts.CollarButton'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='cuff_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuff_button', to='shirts.CuffButton'),
        ),
    ]
