# Generated by Django 2.1 on 2019-06-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0039_auto_20190622_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='pocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_pocket', to='shirts.Pocket'),
        ),
    ]
